### ISSUE TITLE
server side render support for SEO

### ISSUE THREAD

**Issue by sabakugaara** [NemoAlex/upyun.com#1]

**Comment by NemoAlex** [comment]
I prefer prerendering. I'll add it later.
https://github.com/chrisvfritz/prerender-spa-plugin

**Comment by sabakugaara** [comment]
good for SEO is enough~

**Comment by NemoAlex** [comment]
https://github.com/NemoAlex/upyun.com/commit/79d8eef91a672921e928807249b99ae6a167c06e

**Comment by sabakugaara** [comment]
when I use `npm run prerender`, product menu not work

**Comment by NemoAlex** [comment]
hum... seems like JS stoped by a error.
I'll fix it later.

**Comment by NemoAlex** [comment]
Fixed
https://github.com/NemoAlex/upyun.com/commit/475ae2d6c7e871df3e66324b9e1d98d66a9cb319

**Comment by sabakugaara** [comment]
works well now
